# example-node1-bmh-secret & assisted-deployment-pull-secret need to be created under same namespace demo-ztp-gitops
---
apiVersion: ran.openshift.io/v1
kind: SiteConfig
metadata:
  name: "sno-gitops"
  namespace: "sno-gitops"
spec:
  baseDomain: "sandbox715.opentlc.com"
  pullSecretRef:
    name: "demo-ztp-gitops-pull-secret"
  clusterImageSetNameRef: "img4.16.5-multi-appsub"
  sshPublicKey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCzR2ixpaJIecsCunvgJjg18NEFPPTYKewSa9eD6GMptHNYyybIqYtng/2/AsNSZ9cp54fCqt5QUIsD7OfFJQnN7/1z7sHyeEM5t2PhK1GOykq2klga//HlvCgK3DJTy9az+wq5JVyHLUZnRGtgOQRgYLox2CadThBs2aM8QwSXCDjhIjgApwEvoFuH9yRFAervBNykvIiEx+K8p1w2vkntCn8XsiuZ4xRwNuttiudysCHYq9EkdOHIEt6a+ktR7cxpD8uAoxym4UitoHynCy6Jp7Ji0GNaVNhsE9dkcXjQDmP7s+IRs7s83Om4dDpXzhTAol9++MvHsDjYtEUN5Se/N44jjwyeVXivzF7IjZg1WHJgb1gYiYRUoBhzcqzO8Vft9xdjpS8sZ/46+CQA2XPEw5uxP5iBFHgmzbOYl2GPMr67qK19gtAduXvofSMDiXGkzIPQoXn6xnQjl6QHrn/uCk1q4+76jqYZcRzGj0NNMx4Viu+zws9GLMK9M7arym8="
  clusters:
  - clusterName: "sno-gitops"
    networkType: "OVNKubernetes"
    # installConfigOverrides is a generic way of passing install-config
    # parameters through the siteConfig.  The 'capabilities' field configures
    # the composable openshift feature.  In this 'capabilities' setting, we
    # remove all the optional set of components.
    # Notes:
    # - OperatorLifecycleManager is needed for 4.15 and later
    # - NodeTuning is needed for 4.13 and later, not for 4.12 and earlier
    # - Ingress is needed for 4.16 and later
    installConfigOverrides: |
      {
        "capabilities": {
          "baselineCapabilitySet": "None",
          "additionalEnabledCapabilities": [
            "NodeTuning",
            "OperatorLifecycleManager",
            "marketplace",
            "Ingress"
          ]
        }
      }
    # It is strongly recommended to include crun manifests as part of the additional install-time manifests for 4.13+.
    # The crun manifests can be obtained from source-crs/optional-extra-manifest/ and added to the git repo ie.sno-extra-manifest.
    # extraManifestPath: sno-extra-manifest
    clusterLabels:
      demo: gitops
      cluster.open-cluster-management.io/clusterset: demo-ztp-gitops
      sites : "sno-gitops"
    clusterNetwork:
      - cidr: 10.128.0.0/14
        hostPrefix: 23
    machineNetwork:
      - cidr: 192.168.100.0/24
    serviceNetwork:
      - 172.30.0.0/16
    #additionalNTPSources:
    #  - 2.rhel.pool.ntp.org
    # Initiates the cluster for workload partitioning. Setting specific reserved/isolated CPUSets is done via PolicyTemplate
    # please see Workload Partitioning Feature for a complete guide.
    #cpuPartitioningMode: AllNodes
    # Optionally; This can be used to override the KlusterletAddonConfig that is created for this cluster:
    #crTemplates:
    #  KlusterletAddonConfig: "KlusterletAddonConfigOverride.yaml"
    nodes:
      - hostName: "sno-2.sandbox715.opentlc.com"
        role: "master"
        # Optionally; This can be used to configure desired BIOS setting on a host:
        #biosConfigRef:
        #  filePath: "example-hw.profile"
        bmcAddress: "redfish-virtualmedia+http://bmc.sno-gitops.sandbox715.opentlc.com:8000/redfish/v1/Systems/0d4bcdaa-b659-41b2-9f4f-98cb6712aa2d"
        bmcCredentialsName: 
          name: "demo-ztp-gitops-bmc-secret-1"
        bootMACAddress: "52:54:00:c2:2e:ae"
        # Use UEFISecureBoot to enable secure boot
        bootMode: "UEFI"
        #rootDeviceHints:
        #  deviceName: "/dev/disk/by-path/pci-0000:01:00.0-scsi-0:2:0:0"
        # disk partition at `/var/lib/containers` with ignitionConfigOverride. Some values must be updated. See DiskPartitionContainer.md for more details
        #ignitionConfigOverride: |
        #  {
        #    "ignition": {
        #      "version": "3.2.0"
        #    },
        #    "storage": {
        #      "disks": [
        #        {
        #          "device": "/dev/disk/by-id/wwn-0x6b07b250ebb9d0002a33509f24af1f62",
        #          "partitions": [
        #            {
        #              "label": "var-lib-containers",
        #              "sizeMiB": 0,
        #              "startMiB": 250000
        #            }
        #          ],
        #          "wipeTable": false
        #        }
        #      ],
        #      "filesystems": [
        #        {
        #          "device": "/dev/disk/by-partlabel/var-lib-containers",
        #          "format": "xfs",
        #          "mountOptions": [
        #            "defaults",
        #            "prjquota"
        #          ],
        #          "path": "/var/lib/containers",
        #          "wipeFilesystem": true
        #        }
        #      ]
        #    },
        #    "systemd": {
        #      "units": [
        #        {
        #          "contents": "# Generated by Butane\n[Unit]\nRequires=systemd-fsck@dev-disk-by\\x2dpartlabel-var\\x2dlib\\x2dcontainers.service\nAfter=systemd-fsck@dev-disk-by\\x2dpartlabel-var\\x2dlib\\x2dcontainers.service\n\n[Mount]\nWhere=/var/lib/containers\nWhat=/dev/disk/by-partlabel/var-lib-containers\nType=xfs\nOptions=defaults,prjquota\n\n[Install]\nRequiredBy=local-fs.target",
        #          "enabled": true,
        #          "name": "var-lib-containers.mount"
        #        }
        #      ]
        #    }
        #  }
        nodeNetwork:
          interfaces:
            - name: eth0
              macAddress: "52:54:00:c2:2e:ae"
          config:
            interfaces:
              - name: eth0
                type: ethernet
                state: up
                ipv4:
                  enabled: true
                  address:
                    - ip: 192.168.100.3
                      prefix-length: 24
                  dhcp: false
            dns-resolver:
              config:
                search:
                - example.com
                server:
                - 8.8.8.8
            routes:
              config:
              - destination: 0.0.0.0/0
                next-hop-address: 192.168.100.1
                next-hop-interface: eth0
                table-id: 254
