---
- name: Generate Libreswan configuration from AWS Generic VPN config
  hosts: localhost
  gather_facts: no
  vars_files:
    - vars.yaml
  tasks:
    - name: Read the generic VPN configuration file
      slurp:
        src: "{{ vpn_config_file }}"
      register: vpn_config_content

    - name: Decode and parse the VPN configuration
      set_fact:
        vpn_config: "{{ vpn_config_content['content'] | b64decode }}"

    - name: Extract values from the configuration (Tunnel 1 and 2)
      set_fact:
        local_internal_ip_tunnel_1: "{{ (vpn_config | regex_search('Inside IP Addresses\\n\\s+- Customer Gateway\\s+:\\s+([\\d./]+)', '\\1')) | first }}"
        pre_shared_key_tunnel_1: "{{ (vpn_config | regex_search('Pre-Shared Key\\s+:\\s+([\\w\\d\\.-]+)', '\\1')) | first }}"
        customer_gateway_ip_tunnel_1: "{{ (vpn_config | regex_search('Customer Gateway\\s+:\\s+([\\d.]+)', '\\1')) | first }}"
        vpg_ip_tunnel_1: "{{ (vpn_config | regex_search('Virtual Private Gateway\\s+:\\s+([\\d.]+)', '\\1')) | first }}"
        #phase1_encryption_algorithm: "{{ (vpn_config | regex_search('Encryption Algorithm\\s+:\\s+([\\w-]+)', '\\1')) | first }}"
        phase1_encryption_algorithm: "aes128"
        phase1_auth_algorithm: "{{ (vpn_config | regex_search('Authentication Algorithm\\s+:\\s+(\\w+)', '\\1')) | first }}"
        mtu_size: "{{ vpn_config | regex_search('Tunnel interface MTU\\s+:\\s+(\\d+)', '\\1') }}"
        dpd_interval: "{{ (vpn_config | regex_search('DPD Interval\\s+:\\s+(\\d+)', '\\1')) | first }}"
        dpd_retries: "{{ (vpn_config | regex_search('DPD Retries\\s+:\\s+(\\d+)', '\\1')) | first }}"
        ike_version: "ikev2"
        dh_group: "modp2048"


    - name: Create /etc/ipsec.conf file
      copy:
        dest: "{{ libreswan_config_file | default('../openwrt_ipsec.conf') }}"
        content: |
          config setup
            uniqueids=no

          conn aws-vpn-tunnel
            authby=secret
            left={{ local_internal_ip_tunnel_1.split('/')[0] }}
            leftid={{ customer_gateway_ip_tunnel_1 }}
            leftsubnet={{ local_ipv4_cidr }}
            right={{ vpg_ip_tunnel_1 }}
            rightsubnet={{ remote_ipv4_cidr }}
            ike={{ phase1_encryption_algorithm }}-{{ phase1_auth_algorithm }}-{{ dh_group }}
            ikelifetime=28800s
            dpdaction=restart
            dpddelay={{ dpd_interval }}
            dpdtimeout=30
            auto=start


    - name: Create /etc/ipsec.secrets file
      copy:
        dest: "{{ libreswan_secrets_file | default('../openwrt_ipsec.secrets') }}"
        content: |
          {{ customer_gateway_ip_tunnel_1 }} {{ vpg_ip_tunnel_1 }} : PSK "{{ pre_shared_key_tunnel_1 }}"


    - name: Create /etc/config/network file
      copy:
        dest: "{{ output_network_file | default('../openwrt_network') }}"
        content: |
          config interface 'vti1'
            option proto 'vti'
            option mtu '1500'
            option tunlink '{{ interface_name }}'
            option peeraddr '{{ vpg_ip_tunnel_1 }}'
            option zone 'vpn'
            option ikey '100'
            option okey '100'

          config interface 'vti1_static'
            option proto 'static'
            option device '@vti1'
            list ipaddr '{{ local_internal_ip_tunnel_1 }}'

          config route
            option target '{{ remote_ipv4_cidr }}'
            option interface 'vti1_static'



    - name: Create /etc/config/firewall file
      copy:
        dest: "{{ output_firewall_file | default('../openwrt_firewall') }}"
        content: |
          config 'zone'
            option 'name' 'vpn'
            option 'network' 'vti1'
            option 'input' 'ACCEPT'
            option 'output' 'ACCEPT'
            option 'forward' 'ACCEPT'
            option 'mtu_fix' '1'
          
          config 'forwarding'
            option 'src' 'lan'
            option 'dest' 'vpn'
          
          config 'forwarding'
            option 'src' 'vpn'
            option 'dest' 'lan'
          
          config 'rule'
            option 'name' 'Allow-IPSec-ESP'
            option 'src' 'wan'
            option 'proto' 'esp'
            option 'family' 'ipv4'
            option 'target' 'ACCEPT'
          
          config 'rule'
            option 'name' 'Allow-ISP-ISAKMP'
            option 'src' 'wan'
            option 'src_port' '500'
            option 'dest_port' '500'
            option 'proto' 'udp'
            option 'family' 'ipv4'
            option 'target' 'ACCEPT'

    - name: Next steps
      debug:
        msg: |
          1) Append the contents of network file into /etc/config/network and restart with '/etc/init.d/network restart'
          2) Append the contents of firewall file into /etc/config/firewall and restart with '/etc/init.d/firewall restart'

