apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: demo-placement
  namespace: openshift-gitops
spec:
  clusterSets:
    - cloud
    - near-edge
  numberOfClusters: 1
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchLabels:
            demo: demo-placement 
  tolerations:
    - key: demo-placement-service
      value: "endpoint"
      operator: Equal
    - key: demo-placement-service
      value: "inference"
      operator: Equal
    - key: demo-placement-service
      value: "backend"
      operator: Equal
  prioritizerPolicy:
    configurations:
      - scoreCoordinate:
          builtIn: ResourceAllocatableCPU
        weight: 2
      - scoreCoordinate:
          builtIn: ResourceAllocatableMemory
        weight: 2