---
- name: Create AWS VPN connection and enable route propagation
  hosts: localhost
  gather_facts: no
  vars_files:
    - vars.yaml

  tasks:
    - name: Gather information about existing VPCs
      amazon.aws.ec2_vpc_net_info:
        region: "{{ aws_region }}"
      register: vpc_facts

    - name: Select the first VPC if vpc_id is not provided
      set_fact:
        vpc_id: "{{ vpc_facts.vpcs[0].vpc_id }}"
      when: vpc_id is not defined or vpc_id | length == 0

    - name: Ensure VPC ID is selected
      fail:
        msg: "No VPC found in the account. Please create a VPC first."
      when: vpc_id is not defined or vpc_id | length == 0

    - name: Create Virtual Private Gateway
      community.aws.ec2_vpc_vgw:
        region: "{{ aws_region }}"
        vpc_id: "{{ vpc_id }}"
        state: present
        name: demo-vpn
      register: vgw_result

    - name: Create Customer Gateway
      community.aws.ec2_customer_gateway:
        region: "{{ aws_region }}"
        ip_address: "{{ customer_gateway_ip }}"
        state: present
        name: demo-vpn
        routing: static
      register: cgw_result

    - name: Create Site-to-Site VPN connection
      community.aws.ec2_vpc_vpn:
        region: "{{ aws_region }}"
        state: present
        static_only: true
        customer_gateway_id: "{{ cgw_result.gateway.customer_gateway.customer_gateway_id }}"
        vpn_gateway_id: "{{ vgw_result.vgw.id }}"
        routes:
          - "{{ local_ipv4_cidr }}"
      register: vpn_result

    - name: Get information about existing VPC route tables
      amazon.aws.ec2_vpc_route_table_info:
        region: "{{ aws_region }}"
        filters:
          vpc-id: "{{ vpc_id }}"
      register: existing_route_tables

    - name: Enable route propagation for existing route tables
      amazon.aws.ec2_vpc_route_table:
        region: "{{ aws_region }}"
        lookup: id
        route_table_id: "{{ item.route_table_id }}"
        purge_routes: "no"
        purge_subnets: "no"
        purge_tags: "no"
        vpc_id: "{{ item.vpc_id }}"
        propagating_vgw_ids:
          - "{{ vgw_result.vgw.id }}"
      loop: "{{ existing_route_tables.route_tables }}"


    - name: Gather existing security groups in the VPC
      amazon.aws.ec2_security_group_info:
        region: "{{ aws_region }}"
        filters:
          vpc-id: "{{ vpc_id }}"
      register: sg_facts

    - name: Add inbound rule to all security groups
      amazon.aws.ec2_security_group:
        name: "{{ item.group_name }}"
        description: "{{ item.description }}"
        region: "{{ aws_region }}"
        state: present
        group_id: "{{ item.group_id }}"
        vpc_id: "{{ vpc_id }}"
        purge_rules: false
        purge_rules_egress: false
        purge_tags: false
        rules:
          - proto: all
            from_port: 0
            to_port: 65535
            cidr_ip: "{{ local_ipv4_cidr }}"
        rules_egress:
          - proto: all
            from_port: 0
            to_port: 65535
            cidr_ip: "{{ local_ipv4_cidr }}"
      loop: "{{ sg_facts.security_groups }}"



    - name: Output VPN details
      debug:
        msg: "VPN connection created. Go to AWS console and download the appropiate config file for your system."
