---
- name: Delete AWS VPN connection and associated resources
  hosts: localhost
  gather_facts: no
  vars_files:
    - vars.yaml

  tasks:

    - name: Gather information about existing VPCs
      amazon.aws.ec2_vpc_net_info:
        region: "{{ aws_region }}"
      register: vpc_facts

    - name: Select the first VPC if vpc_id is not provided
      set_fact:
        vpc_id: "{{ vpc_facts.vpcs[0].vpc_id }}"
      when: vpc_id is not defined or vpc_id | length == 0

    - name: Ensure VPC ID is selected
      fail:
        msg: "No VPC found in the account. Please create a VPC first."
      when: vpc_id is not defined or vpc_id | length == 0

    - name: Gather information about existing Customer Gateways
      community.aws.ec2_customer_gateway_info:
        region: "{{ aws_region }}"
        filters:
          ip-address: "{{ customer_gateway_ip }}"
      register: cgw_info

    - name: Ensure Customer Gateway exists
      fail:
        msg: "No Customer Gateway found with the IP address {{ customer_gateway_ip }}."
      when: cgw_info.customer_gateways | length == 0

    - name: Set customer_gateway_id fact
      set_fact:
        customer_gateway_id: "{{ cgw_info.customer_gateways[0].customer_gateway_id }}"

    - name: Gather information about existing Customer Gateways
      community.aws.ec2_customer_gateway_info:
        region: "{{ aws_region }}"
        filters:
          ip-address: "{{ customer_gateway_ip }}"
      register: cgw_info

    - name: Gather information about existing VPN connections
      community.aws.ec2_vpc_vpn_info:
        region: "{{ aws_region }}"
        filters:
          customer-gateway-id: "{{ customer_gateway_id }}"
      register: vpn_info


    - name: Delete Site-to-Site VPN connection
      community.aws.ec2_vpc_vpn:
        region: "{{ aws_region }}"
        state: absent
        vpn_connection_id: "{{ item.vpn_connection_id }}"
      loop: "{{ vpn_info.vpn_connections }}"
      when: vpn_info.vpn_connections | length > 0

    - name: Gather information about the existing Virtual Private Gateways
      community.aws.ec2_vpc_vgw_info:
        region: "{{ aws_region }}"
        filters:
          attachment.vpc-id: "{{ vpc_id }}"
      register: vgw_info

    - name: Detach Virtual Private Gateway from VPC
      community.aws.ec2_vpc_vgw:
        region: "{{ aws_region }}"
        state: absent
        vpc_id: "{{ vpc_id }}"
        vpn_gateway_id: "{{ item.vpn_gateway_id }}"
      loop: "{{ vgw_info.virtual_gateways }}"
      when: vgw_info.virtual_gateways | length > 0

    - name: Delete Virtual Private Gateway
      community.aws.ec2_vpc_vgw:
        region: "{{ aws_region }}"
        state: absent
        vpn_gateway_id: "{{ item.vpn_gateway_id }}"
      loop: "{{ vgw_info.virtual_gateways }}"
      when: vgw_info.virtual_gateways | length > 0

    - name: Delete Customer Gateway
      community.aws.ec2_customer_gateway:
        region: "{{ aws_region }}"
        state: absent
        routing: static
        ip_address: "{{ customer_gateway_ip }}"
        name: "demo-vpn"

