[allowlist]
  description = "Global Allowlist"

  # Ignore based on any subset of the file path
  paths = [
    '''demos\/ztp\/demo-manifests\/siteconfig\/ztp-bmc-secret.yaml.example''',

    '''demos\/ztp\/demo-manifests\/siteconfig\/ztp-pull-secret.yaml.example''',

    '''demos\/ztp\/demo-manifests\/siteconfig\/demo-ztp.yaml''',

  ]
        
