---
- name: Create AWS VPN connection
  hosts: localhost
  gather_facts: no
  vars_files:
    - vars.yaml

  tasks:
    - name: Gather information about existing VPCs
      amazon.aws.ec2_vpc_net_info :
        region: "{{ aws_region }}"
      register: vpc_facts

    - name: Select the first VPC if vpc_id is not provided
      set_fact:
        vpc_id: "{{ vpc_facts.vpcs[0].vpc_id }}"
      when: vpc_id is not defined or vpc_id | length == 0

    - name: Ensure VPC ID is selected
      fail:
        msg: "No VPC found in the account. Please create a VPC first."
      when: vpc_id is not defined or vpc_id | length == 0

    - name: Create Virtual Private Gateway
      community.aws.ec2_vpc_vgw:
        region: "{{ aws_region }}"
        vpc_id: "{{ vpc_id }}"
        state: present
        name: demo-vpn
      register: vgw_result

    - name: Create Customer Gateway
      community.aws.ec2_customer_gateway:
        region: "{{ aws_region }}"
        ip_address: "{{ customer_gateway_ip }}"
        bgp_asn: "{{ customer_gateway_asn }}"
        state: present
        name: demo-vpn
      register: cgw_result

    - name: Create Site-to-Site VPN connection
      community.aws.ec2_vpc_vpn:
        region: "{{ aws_region }}"
        state: present
        customer_gateway_id: "{{ cgw_result.gateway.customer_gateway.customer_gateway_id }}"
        vpn_gateway_id: "{{ vgw_result.vgw.id }}"
      register: vpn_result

    - name: Download VPN configuration
      community.aws.ec2_vpc_vpn:
        region: "{{ aws_region }}"
        vpn_connection_id: "{{ vpn_result.vpn_connection.id }}"
        state: present
        download_config: true
        config_path: "vpn-config.txt"
        config_format: generic

    - name: Output VPN details
      debug:
        msg: "VPN connection created. Go to AWS console and download the appropiate config file for your system."
