apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: placement-argocd-demo-ztp-gitops
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "19"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  clusterSets:
    - demo-ztp-gitops