apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: "common"
policyDefaults:
    namespace: sno-gitops
    remediationAction: enforce
    severity: high
    namespaceSelector:
        exclude:
            - kube-*
        include:
            - '*'
    evaluationInterval:
        compliant: 10m
        noncompliant: 10s
policies:
    - name: demo-ztp-gui-operators
      policyAnnotations:
        ran.openshift.io/ztp-deploy-wave: "4"
      disabled: false
      manifests:
        - path: policies/
          patches:
            - apiVersion: policy.open-cluster-management.io/v1
              kind: Policy
              metadata:
                name: demo-ztp-gitops-operators
                namespace: sno-gitops