apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: "common"
policyDefaults:
    namespace: sno-gitops-policy
    remediationAction: enforce
    severity: high
    evaluationInterval:
        compliant: 10m
        noncompliant: 10s
    placement:
      placementPath: input/placement.yaml
policies:
    - name: demo-ztp-gitops
      policyAnnotations:
        ran.openshift.io/ztp-deploy-wave: "4"
      disabled: false
      manifests:
        - path: input/policy-manifests/
policySets:
  - name: demo-ztp-gitops
    description: "PolicySet for demo-ztp-gitops"
    policies:
      - demo-ztp-gitops
bindings:
  - name: demo-ztp-gitops-binding
    placementRef:
      kind: Placement
      name: placement-policy
      apiGroup: cluster.open-cluster-management.io
    subjects:
      - kind: PolicySet
        name: demo-ztp-gitops
        apiGroup: policy.open-cluster-management.io