apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: "common"
policyDefaults:
    namespace: sno-gitops-policy
    remediationAction: enforce
    severity: high
    evaluationInterval:
        compliant: 10m
        noncompliant: 10s
    placement:
      placementPath: input/placement.yaml
    placementBindingDefaults:
      name: demo-ztp-gitops
policies:
    - name: demo-ztp-gitops
      policyAnnotations:
        ran.openshift.io/ztp-deploy-wave: "4"
      disabled: false
      manifests:
        - path: input/policy-manifests/
      policySets:
        - demo-ztp-gitops
policySets:
  - name: demo-ztp-gitops
    description: "PolicySet for demo-ztp-gitops"
    policies:
      - demo-ztp-gitops
    placement:
      placementPath: input/placement.yaml
