apiVersion: v1
baseDomain: "{{ appliance_basedomain }}"
compute:
- architecture: amd64 
  hyperthreading: Enabled
  name: worker
  replicas: 0
controlPlane:
  architecture: amd64
  hyperthreading: Enabled
  name: master
  replicas: 1
metadata:
  name: "{{ appliance_name }}"
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineNetwork:
  - cidr: 192.168.0.0/16
  networkType: OVNKubernetes 
  serviceNetwork:
  - 172.30.0.0/16
platform:
  none: {}
capabilities:
  baselineCapabilitySet: None
  additionalEnabledCapabilities:
  - NodeTuning
  - OperatorLifecycleManager
  - Marketplace
  - Ingress
pullSecret: '{{ pull_secret }}'
sshKey: "{{ ssh_key }}"