apiVersion: v1
metadata:
  name: "{{ appliance_name }}"
baseDomain: "{{ appliance_basedomain }}"
controlPlane:
  name: master
  replicas: 1
compute:
- name: worker
  replicas: 0
networking:
  networkType: OVNKubernetes
  machineNetwork:
  - cidr: 192.168.122.0/24
platform:
  none: {}
pullSecret: '{{ pull_secret }}'
sshKey: "{{ ssh_key }}"