apps:
  - name: people-counter-inference
    namespace: openshift-gitops
    repoURL: 'https://github.com/luisarizmendi/openshift-edge-demos.git'
    path: demos/ai-edge/people-counter-inference/resources/hello
    placement: people-counter-inference
    revision: main
    project: ai-edge
    extra: |
        helm:
          valueFiles:
              - values.yaml
              - environments/'{{ .environment }}'/values.yaml     
