{{- range .Values.clusters }}
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: {{ $.Values.app.name }}-{{ .name }}
  namespace: {{ $.Values.app.namespace }}
  labels:
    app.kubernetes.io/managed-by: {{ $.Values.app.name }}-{{ .name }}
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: {{ $.Values.app.repoURL }}
        revision: {{ $.Values.app.revision }}
        directories:
        {{- range $.Values.app.directories }}
        - path: {{ . }}
        {{- end }}
  template:
    metadata:
      name: {{`{{.path.basename}}`}}-{{ .name }}
    spec:
      project: {{ $.Values.app.project }}
      source:
        repoURL: {{ $.Values.app.repoURL }}
        targetRevision: {{ $.Values.app.revision }}
        path: '{{`{{.path.path}}`}}'
        helm:
          valueFiles:
              - values.yaml
              - environment/values-{{ .name }}.yaml
      destination:
        server: '{{ .server }}'
        namespace: '{{`{{.path.basename}}`}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
---
{{- end }}