apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: "common"
  namespace: "ztp-common"
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
placementBindingDefaults:
    name: common-placement-binding

policies:
    - name: common-hello-app
      policyAnnotations:
        ran.openshift.io/ztp-deploy-wave: "1"
      disabled: false
      manifests:
        - path: ../../../apps/welcome/hello-app
          patches:
            - apiVersion: v1
              kind: ConfigMap
              metadata:
                name: hello-world-configmap
                namespace: hello-world
                labels:
                  app.kubernetes.io/instance: hello-world
              data:
                "index.html": |-
                  <!DOCTYPE html>
                    <html lang="en">
                      <head>
                        <meta charset="utf-8">
                        <title>Hello World</title>
                      </head>
                        <body>
                          <h1>Hi!</h1>
                          <br/>
                          <h2>
                          I've been created by a PolicyGenerator<br>
                          </h2>
                        </body>
                    </html>