---
apiVersion: ran.openshift.io/v1
kind: PolicyGenTemplate
metadata:
  name: "common"
  namespace: "ztp-common"
spec:
  bindingRules:
    # These policies will correspond to all clusters with this label:
    common: "true"
  sourceFiles:
    # Create operators policies that will be installed in all clusters

    # Enable Web Terminal
    - fileName: web-terminal/namespace.yaml
      policyName: "web-terminal-policy"
    - fileName: web-terminal/operator-group.yaml
      policyName: "web-terminal-policy"
    - fileName: web-terminal/subscription.yaml
      policyName: "web-terminal-policy"
    - fileName: web-terminal/status.yaml
      policyName: "web-terminal-policy"



  ---
apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: "common"
  namespace: "ztp-common"
placementBindingDefaults:
    name: common-placement-binding
policyDefaults:
    namespace: ztp-common
    placement:
        labelSelector:
            matchExpressions:
                - key: common
                  operator: In
                  values:
                    - "true"
                - key: du-profile
                  operator: In
                  values:
                    - latest
    remediationAction: inform
    severity: low
    namespaceSelector:
        exclude:
            - kube-*
        include:
            - '*'
    evaluationInterval:
        compliant: 10m
        noncompliant: 10s
policies:
    - name: common-config-policy
      policyAnnotations:
        ran.openshift.io/ztp-deploy-wave: "1"
      manifests:
        - path: source-crs/OperatorHub.yaml