{{- range .Values.environments }}
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: demo-placement-{{ .name }}
  namespace: openshift-gitops
spec:
  generators:
    - clusterDecisionResource:
        configMapRef: acm-placement
        labelSelector:
          matchLabels:
            cluster.open-cluster-management.io/placement: demo-placement
        requeueAfterSeconds: 180
  template:
    metadata:
      name: people-counter-inference-hello-{{name}}
    spec:
      project: demo-placement
      source:
        repoURL: 'https://github.com/luisarizmendi/openshift-edge-demos.git'
        targetRevision: main
        path: demos/demo-placement/people-counter-inference/resources/hello
        helm:
          valueFiles:
              - values.yaml
              - environments/cloud/values.yaml    
      destination:
        server: "{{server}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
---
{{- end }}

