

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uploads-pvc
  namespace: openshift-pipelines-vms
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-server-upload
  namespace: openshift-pipelines-vms
  labels:
    app: http-server-upload
spec:
  replicas: 1
  selector:
    matchLabels:
      app: http-server-upload
  template:
    metadata:
      labels:
        app: http-server-upload
    spec:
      containers:
      - name: http-server-upload
        image: quay.io/luisarizmendi/http-server-upload:latest
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: uploads
          mountPath: /app/uploads
      volumes:
      - name: uploads
        persistentVolumeClaim:
          claimName: uploads-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: http-server-upload
  namespace: openshift-pipelines-vms
spec:
  type: ClusterIP
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: http-server-upload
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: http-server-upload
  namespace: openshift-pipelines-vms
spec:
  to:
    kind: Service
    name: http-server-upload
  port:
    targetPort: 5000
  wildcardPolicy: None
