apiVersion: v1beta1
kind: AgentConfig
metadata:
  name: "{{ appliance_name }}"
rendezvousIP: "{{ appliance_rendezvous }}"
## Static IP
hosts:
  - hostname: sno-appliance
    interfaces:
      - name: eth0
        macAddress: 52:54:00:e3:d7:2a
    networkConfig:
      interfaces:
        - name: eth0
          type: ethernet
          state: up
          mac-address: 52:54:00:e3:d7:2a
          ipv4:
            enabled: true
            address:
              - ip: 192.168.122.30
                prefix-length: 24
            dhcp: false
      dns-resolver:
        config:
          server:
            - 8.8.8.8
      routes:
        config:
          - destination: 0.0.0.0/0
            next-hop-address: 192.168.122.1
            next-hop-interface: eth0
            table-id: 254

