---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: ai-edge
  namespace: openshift-gitops
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    server: '*'
  sourceRepos:
  - '*'