---
- name: Generate Cluster Configuration Image
  hosts: localhost
  gather_facts: no

  vars_files:
    - vars.yaml
    - vars_secret.yaml

  tasks:
    - name: Remove old directories
      become: true
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      with_items:
        - "tmp-files/image-config"
        - "../output/image-config"

    - name: Ensure directories exists
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ appliance_assets_config_iso }}"
        - "tmp-files/config"
        - "../output/image-config"

    - name: Check for install-config.yaml
      ansible.builtin.stat:
        path: "{{ install_config_file_template }}"
      register: install_config_file_check

    - name: Configure install-config.yaml
      ansible.builtin.template:
        src: "{{ install_config_file_template }}"
        dest: "tmp-files/image-config/install-config.yaml"
      when: install_config_file_check.stat.exists

    - name: Backup install-config.yaml
      ansible.builtin.template:
        src: "{{ install_config_file_template }}"
        dest: "../output/image-config/install-config.yaml"
      when: install_config_file_check.stat.exists

    - name: Check for agent-config.yaml"
      ansible.builtin.stat:
        path: "{{ agent_config_file }}"
      register: agent_config_file_check

    - name: Configure agent-config.yaml"
      ansible.builtin.template:
        src: "{{ agent_config_file }}"
        dest: "tmp-files/image-config/agent-config.yaml"
      when: agent_config_file_check.stat.exists

    - name: Backup agent-config.yaml"
      ansible.builtin.template:
        src: "{{ agent_config_file }}"
        dest: "../output/image-config/agent-config.yaml"
      when: agent_config_file_check.stat.exists

    - name: Create openshift manifests directory (if needed)
      ansible.builtin.file:
        path: "tmp-files/image-config/openshift"
        state: directory
      when: custom_manifests_dir is defined and custom_manifests_dir | length > 0

    - name: Add custom manifests to the cluster config directory
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "tmp-files/image-config/openshift/{{ item | basename }}"
      with_fileglob:
        - "{{ custom_manifests_dir }}/**/*.yaml"
        - "{{ custom_manifests_dir }}/**/*.yml"
      when: custom_manifests_dir is defined and custom_manifests_dir | length > 0

    - name: Generate the configuration image
      ansible.builtin.command:
        cmd: "openshift-install agent create config-image --dir tmp-files/image-config/"
      register: config_image_result
      ignore_errors: yes


    - name: Move the results to output directory 
      ansible.builtin.shell: "mv -f tmp-files/image-config/{{ item }} ../output/image-config"
      with_items:
        - auth/
        - agentconfig.noarch.iso



