## Common
ssh_key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

## Image creation
appliance_image: "quay.io/edge-infrastructure/openshift-appliance:312437b82905331f5ce56af7699c961fe195f3213986c71b09effa65308aa900"

appliance_assets_image: "../../../demos/ztp/demo-manifests/02-appliance/00-image-base"
appliance_config_file: "{{ appliance_assets_image }}/appliance-config-template.yaml"
custom_manifests_dir: "{{ appliance_assets_image }}/custom-manifests"
custom_images_file: "{{ appliance_assets_image }}/custom-images.yaml"
custom_operators_file: "{{ appliance_assets_image }}/custom-operators.yaml"
iso_post_deployment_script: "{{ appliance_assets_image }}/iso-post-deployment.sh"

user_core_pass: "R3dh4t1!"
ocp_release_version: "4.16.9"
ocp_release_channel: "stable"
cpu_architecture: "x86_64"
disk_size_gb: 200


## Config generation
appliance_name: "ocp-appliance"
appliance_basedomain: "sandbox184.opentlc.com"
appliance_target_dev: /dev/sda

appliance_rendezvous: 192.168.140.3
appliance_machine_network: "192.168.140.0/24"

appliance_assets_config_iso: "../../../demos/ztp/demo-manifests/02-appliance/01-image-config"
install_config_file_template: "{{ appliance_assets_config_iso }}/install-config-template.yaml"
agent_config_file: "{{ appliance_assets_config_iso }}/agent-config-template.yaml"
manifests_dir_config_iso: "{{ appliance_assets_config_iso }}/manifests"




